apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  restartPolicy: Always
  containers:
  - name: kube-proxy
    image: gcr.io/google-containers/hyperkube:{K8S_VERSION}
    command:
    - kube-proxy
    - --config={K8S_BASE_PATH}/kube-proxy-config.yaml
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: {K8S_SSL_PATH}
      name: etc-kube-ssl
      readOnly: true
    - mountPath: {K8S_BASE_PATH}/admin.yaml
      name: kubeconfig
      readOnly: true
    - mountPath: {K8S_BASE_PATH}/kube-proxy-config.yaml
      name: proxy-config
      readOnly: true
  volumes:
  - hostPath:
      path: {K8S_BASE_PATH}/admin.yaml
    name: kubeconfig
  - hostPath:
      path: {K8S_BASE_PATH}/kube-proxy-config.yaml
    name: proxy-config
  - hostPath:
      path: {K8S_SSL_PATH}
    name: etc-kube-ssl