apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    certificate-authority: {K8S_SSL_PATH}/ca.pem
    server: {API_SERVER_ENDPOINT}
users:
- name: system:kube-controller-manager
  user:
    client-certificate: {K8S_SSL_PATH}/controller-manager.pem
    client-key: {K8S_SSL_PATH}/controller-manager-key.pem
contexts:
- context:
    cluster: kubernetes
    user: system:kube-controller-manager
  name: system:kube-controller-manager@kubernetes
current-context: system:kube-controller-manager@kubernetes