apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    certificate-authority: {K8S_SSL_PATH}/ca.pem
    server: {API_SERVER_ENDPOINT}
users:
- name: system:kube-scheduler
  user:
    client-certificate: {K8S_SSL_PATH}/scheduler.pem
    client-key: {K8S_SSL_PATH}/scheduler-key.pem
contexts:
- context:
    cluster: kubernetes
    user: system:kube-scheduler
  name: system:kube-scheduler@kubernetes
current-context: system:kube-scheduler@kubernetes